apiVersion: batch/v1
kind: Job
metadata:
  generateName: pvc-data-copy-job-
  labels:
    kueue.x-k8s.io/queue-name:  eidf151ns-user-queue
spec:
  template:
    spec:
      containers:
      - name: data-copy
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args: ["cp -rv /src/. /dest/"]
        resources:
          requests:
            cpu: 8
            memory: '32Gi'
          limits:
            cpu: 8
            memory: '32Gi'
        volumeMounts:
        - name: source-pvc
          mountPath: /src
        - name: dest-pvc
          mountPath: /dest
      restartPolicy: Never
      volumes:
      - name: source-pvc
        persistentVolumeClaim:
          claimName: ar-dp-pvc # Change this - original source PVC
      - name: dest-pvc
        persistentVolumeClaim:
          claimName: ar-pvc # Change this - new destination PVC