apiVersion: batch/v1
kind: Job
metadata:
    generateName: $USER-job
    labels:
      eidf/user: $USER
      kueue.x-k8s.io/queue-name: $KUBE_USER_QUEUE
      kueue.x-k8s.io/priority-class: batch-workload-priority
      # kueue.x-k8s.io/priority-class: short-workload-high-priority
spec:
    backoffLimitPerIndex: 0
    # maxFailedIndexes: $N_PODS
    completions: $N_PODS
    completionMode: Indexed
    parallelism: 1
    template:
        metadata:
            labels:
              eidf/user: $USER
        spec:
            restartPolicy: Never
            containers:
            - name: differentiable-patterning
              image: alexdr1998/jax_equinox_scratch:latest
              imagePullPolicy: IfNotPresent
              # command: ["python", "${JOB_PATH_TO_PYTHON_SCRIPT}"]
              command: ["/bin/bash", "-lc"]
              args:
                - "bash ./workspace/launch_inside_pod.sh workspace/$PATH_TO_PYTHON_SCRIPT workspace/$PATH_TO_EXPERIMENT_CONFIG"
              env:
              # - name: MY_USERNAME
                # value: $USER
              - name: JOB_WORKER_INDEX
                value: "$JOB_WORKER_INDEX"
              - name: JOB_WORKER_COUNT
                value: "$JOB_WORKER_COUNT"
              volumeMounts:
                - name: workspace
                  mountPath: /workspace
                  readOnly: true
                - name: writeable
                  mountPath: /workspace/writeable
              resources:
                limits:
                  cpu: 2
                  memory: "16Gi"
                  nvidia.com/gpu: 0
            # nodeSelector:
                # nvidia.com/gpu.product: NVIDIA-H100-80GB-HBM3
                # nvidia.com/gpu.product: NVIDIA-A100-SXM4-80GB
            volumes:
              - name: workspace
                nfs:
                  server: $EIDF107_USER_DATA_NFS_HOST_IP
                  path: $WORKING_DIR
              - name: writeable
                persistentVolumeClaim:
                  claimName: $USER-ws1


