apiVersion: batch/v1
kind: Job
metadata:
    generateName: $USER-job
    labels:
      eidf/user: $USER
      kueue.x-k8s.io/queue-name: $KUBE_USER_QUEUE
      kueue.x-k8s.io/priority-class: batch-workload-priority
      # kueue.x-k8s.io/priority-class: short-workload-high-priority
spec:
    backoffLimitPerIndex: 0
    # maxFailedIndexes: $N_PODS
    completions: $N_PODS
    completionMode: Indexed
    parallelism: 1
    template:
        metadata:
            labels:
              eidf/user: $USER
        spec:
            restartPolicy: Never
            containers:
            - name: differentiable-patterning
              image: alexdr1998/jax_equinox_scratch:latest
              imagePullPolicy: IfNotPresent
              # imagePullPolicy: Always
              # command: ["python", "${JOB_PATH_TO_PYTHON_SCRIPT}"]
              command: ["/bin/bash", "-lc"]
              args:
                - "bash /workspace/launch_inside_pod.sh /workspace/$PATH_TO_PYTHON_SCRIPT /workspace/$PATH_TO_EXPERIMENT_CONFIG"
              env:
              # - name: MY_USERNAME
                # value: $USER
              - name: JOB_WORKER_INDEX
                value: "$JOB_WORKER_INDEX"
              - name: JOB_WORKER_COUNT
                value: "$JOB_WORKER_COUNT"
              - name: PVC_PATH
                value: /workspace
              - name: DATA_PATH_BASE
                value: /workspace/writeable/Data/
              - name: MODEL_SAVE_PATH
                value: /workspace/writeable/Models/
              - name: XLA_PYTHON_CLIENT_MEM_FRACTION
                value: "0.9"
              # - name: XLA_FLAGS
                # value: "--xla_gpu_enable_latency_hiding_scheduler=true"
                # value: "--xla_gpu_enable_latency_hiding_scheduler=true --xla_gpu_triton_gemm_any=True"
                # value: "--xla_gpu_triton_gemm_any=True"
                # value: "--xla_gpu_enable_command_buffer=FUSION"
              - name: WANDB_DIR
                value: /workspace/writeable/wandb-fast
              - name: WANDB_CACHE_DIR
                value: /workspace/writeable/wandb-fast/cache
              - name: WANDB_FLUSH_INTERVAL
                value: "60"
              - name: WANDB_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: $USER-wandb-login
                    key: WANDB_API_KEY
              volumeMounts:
                - name: workspace
                  mountPath: /workspace
                  readOnly: true
                - name: writeable
                  mountPath: /workspace/writeable
                - name: wandb-fast
                  mountPath: /workspace/writeable/wandb-fast
              resources:
                limits:
                  cpu: 8
                  memory: $GPU_MEM_LIMIT
                  nvidia.com/gpu: 1
            nodeSelector:
                nvidia.com/gpu.product: $GPU_TYPE
                # nvidia.com/gpu.product: NVIDIA-H100-80GB-HBM3
                # nvidia.com/gpu.product: NVIDIA-H200
                # nvidia.com/gpu.product: NVIDIA-A100-SXM4-80GB
            volumes:
              - name: workspace
                nfs:
                  server: $EIDF107_USER_DATA_NFS_HOST_IP
                  path: $WORKING_DIR
              - name: writeable
                persistentVolumeClaim:
                  claimName: $USER-ws1
              - name: wandb-fast
                emptyDir: 
                  sizeLimit: 20Gi

