apiVersion: batch/v1
kind: Job
metadata:
  generateName: $USER-job-
  labels:
    eidf/user: $USER
    kueue.x-k8s.io/queue-name: $KUBE_USER_QUEUE
    kueue.x-k8s.io/priority-class: batch-workload-priority
spec:
  backoffLimitPerIndex: 0
  maxFailedIndexes: $N_PODS
  ttlSecondsAfterFinished: 300
  parallelism: 2
  completions: $N_PODS
  completionMode: Indexed
  template:
    metadata:
      labels:
        eidf/user: $USER
    spec:
      restartPolicy: Never
      containers:
      - name: huggingface
        image: huggingface/transformers-pytorch-gpu:latest 
        imagePullPolicy: IfNotPresent
        workingDir: "/workspace"
        command: ["/bin/bash", "-lc"]
        args:
          - "bash ./run_test.sh $((JOB_COMPLETION_INDEX + 1))"
        env:
          - name: MY_USERNAME
            value: $USER
          - name: MY_EXPERIMENT 
            value: experiment2
        resources:
           limits:
            nvidia.com/gpu: 0
            cpu: 2
            memory: 4Gi
        volumeMounts:
          - name: workspace
            mountPath: /workspace
            readOnly: true
          - name: writeable
            mountPath: /workspace/writeable
      # nodeSelector:
      #  nvidia.com/gpu.product: NVIDIA-A100-SXM4-40GB
      volumes:
        - name: workspace
          nfs:
            server: $EIDF107_USER_DATA_NFS_HOST_IP
            path: /user/$USER
        - name: writeable
          persistentVolumeClaim:
             claimName: $USER-ws1
