apiVersion: batch/v1
kind: Job
metadata:
    generateName: ar-dp-job-
    labels:
        kueue.x-k8s.io/queue-name:  eidf151ns-user-queue
spec:
    completions: 1
    template:
        metadata:
            name: ar-dp-pod
        spec:
            restartPolicy: Never
            containers:
            - name: differentiable-patterning
              image: alexdr1998/jax_equinox_scratch:latest
              imagePullPolicy: Always
              command: ["bash","/mnt/ceph/ar-dp/run_multi_gpu.sh"]
              args: ["/mnt/ceph/ar-dp/sae_nca_emoji_train.py","5"]
              #command: ["python3", "/mnt/ceph/ar-dp/sae_nca_emoji_train.py"]
              #command: ["bash", "/mnt/ceph/ar-dp/run_multi_gpu.sh"]
              #command: ["python3", "/mnt/ceph/ar-dp/micropattern_averaged_signalling_channels_eval.py"]
              #command: ["python3", "/mnt/ceph/ar-dp/emoji_aNCA_test.py"]
              volumeMounts:
                - mountPath: /mnt/ceph
                  name: volume
              resources:
                requests:
                  cpu: 48
                  memory: "80Gi"
                limits:
                  cpu: 48
                  memory: "80Gi"
                  nvidia.com/gpu: 5
            nodeSelector:
                nvidia.com/gpu.product: NVIDIA-H100-80GB-HBM3
            volumes:
                - name: volume
                  persistentVolumeClaim:
                    claimName: ar-pvc
